name: Stremio Telegram
version: "1.2.3"
slug: stremio_telegram
description: A self-hosted addon that connects to your Telegram user account, discovers joined private broadcast channels, and indexes uploaded videos for browsing, searching, and streaming through your server

url: https://github.com/hilayc/stremio-addon
image: ghcr.io/hilayc/stremio-addon
webui: "http://[HOST]:[PORT:8001]/"
ingress: true
ingress_port: 8001
ingress_entry: /
arch:
  - amd64
startup: application
boot: auto
init: false
host_network: true
timeout: 30
options:
  port: 8000
  debug_enabled: true
  debug_port: 8001
  debug_host: "0.0.0.0"
  addon_url: ""
  api_key: ""
  api_id: 0
  api_hash: ""
  user_session_string: ""
  cache_mb: 512
  CHANNEL_IDS: ""
schema:
  port: port
  debug_enabled: bool
  debug_port: port
  debug_host: str
  addon_url: url
  api_key: password
  api_id: int(1,)
  api_hash: password
  user_session_string: password
  cache_mb: int(0,)
  CHANNEL_IDS: str?
